name: Update schema files every month
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  update-schemas:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Update Schema
        run: |
          make gen-all-openapi
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated schema files